Repository FlavioLucasFer/agenda, pull requests merged in 2021-11, with the labels that each got.

#32 [BACK-END][FIX] - Corrigir acesso à tela de cadastro de usuário #30
  src/main/java/br/ifpr/agenda/seguranca/ConfiguracaoSeguranca.java
Labels: Back-end, fix

#33 [FRONT-END] - Adicionar botão de logout no header da aplicação #31
  src/main/resources/templates/contatos/editar.html
  src/main/resources/templates/contatos/index.html
Labels: enhancement, Front-end

#34 [FRONT-END][FIX] - Corrigir a tela de login #29
  src/main/java/br/ifpr/agenda/controllers/UsuarioController.java
  src/main/resources/templates/login.html
  src/main/resources/templates/usuarios/cadastrar.html
Labels: Front-end, fix

#36 [FULL-STACK][FIX] - Corrigir bug que faz o select de tipos de telefon…
  src/main/java/br/ifpr/agenda/controllers/ContatoController.java
  src/main/java/br/ifpr/agenda/dominio/Contato.java
Labels: bug, fix, full-stack

#39 [FRONT-END][FIX] - Corrigir bug que faz valores do select de tipos de…
  src/main/java/br/ifpr/agenda/controllers/ContatoController.java
Labels: bug, Front-end, fix

#43 Fix/campos obrigatorios usuario
  src/main/java/br/ifpr/agenda/controllers/UsuarioController.java
  src/main/java/br/ifpr/agenda/dominio/Usuario.java
  src/main/resources/db/migration/V1_0_5__add_unique_constraint_to_email_attr_on_usuario_table.sql
  src/main/resources/templates/usuarios/cadastrar.html
Labels: bug, fix, full-stack

#42 [MIGRATION] - Aplicar regra de registro único no campo email da tabel…
  src/main/resources/db/migration/V1_0_5__add_unique_constraint_to_email_attr_on_usuario_table.sql
Labels: Database, fix

#37 Dev
  .gitignore
  pom.xml
  src/main/java/br/ifpr/agenda/AgendaApplication.java
  src/main/java/br/ifpr/agenda/bootstrap/InicializarDados.java
  src/main/java/br/ifpr/agenda/configuration/DBConfiguration.java
  src/main/java/br/ifpr/agenda/controllers/ContatoController.java
  src/main/java/br/ifpr/agenda/controllers/TipoTelefoneController.java
  src/main/java/br/ifpr/agenda/controllers/UsuarioController.java
  src/main/java/br/ifpr/agenda/dominio/Contato.java
  src/main/java/br/ifpr/agenda/dominio/Endereco.java
  src/main/java/br/ifpr/agenda/dominio/Telefone.java
  src/main/java/br/ifpr/agenda/dominio/TipoTelefone.java
  src/main/java/br/ifpr/agenda/dominio/Usuario.java
  src/main/java/br/ifpr/agenda/repositories/TipoTelefoneRepository.java
  src/main/java/br/ifpr/agenda/repositories/UsuarioRepository.java
  src/main/java/br/ifpr/agenda/seguranca/ConfiguracaoSeguranca.java
  src/main/java/br/ifpr/agenda/seguranca/UserDetailsServiceImpl.java
  src/main/java/br/ifpr/agenda/servicos/UsuarioService.java
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/db/migration/V1_0_0__create_tipo_telefone_table.sql
  src/main/resources/db/migration/V1_0_1__create_usuario_table.sql
  src/main/resources/db/migration/V1_0_2__create_contato_table.sql
  src/main/resources/db/migration/V1_0_3__create_telefone_table.sql
  src/main/resources/db/migration/V1_0_4__create_endereco_table.sql
  src/main/resources/db/migration/V1_0_5__add_unique_constraint_to_email_attr_on_usuario_table.sql
  src/main/resources/flyway.conf.example
  src/main/resources/templates/contatos/editar.html
  src/main/resources/templates/contatos/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/usuarios/cadastrar.html
Labels: enhancement
